version: '3.7'
services:
  blog:
    build: ./blog
    ports: 
      - '3000:3000'
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    ports: 
      - '3306:3306'
    env_file: ./db/.env
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
